export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';

export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const FILTER_PRODUCTS_BY_CONDITION = 'FILTER_PRODUCTS_BY_CONDITION';

export const SORT_BY_PRICE = 'SORT_BY_PRICE';
